= Serial shift register LCD Library for Arduino =

The serial_595_lcd library provides the software interface to use a HD44780 type parallel LCD display
through a 74HC595, so that only (3) digital output pins are required to control it.

This was inspired by those I2C or SPI LCD backpacks from Adafruit.

Only here, well, we just use a 74HC595.

The library requires (3) digital IO pins on your Arduino.

There are some assumptions for how the LCD is connected to the 74HC595, see the
schematic in the doc folder.

For more information about this library please visit us at
https://github.com/marsairforce/595_lcd

== License ==

Copyright (c) 2017 Travis Hein. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
